/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.IU;

import system_control.Controller;
import system_model.Departamento;

/**
 *
 * @author gabri
 */
public class IUCadDepartments extends javax.swing.JFrame {

    /**
     * Creates new form IUCadDepartments
     */
    public IUCadDepartments() {
        initComponents();
        this.setTitle("Departamentos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDepartamentos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNomeDep = new javax.swing.JTextField();
        campoCodDep = new javax.swing.JTextField();
        btnSalvarDep = new javax.swing.JButton();
        btnCancelarDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelDepartamentos.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        labelDepartamentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDepartamentos.setText("CADASTRO DE DEPARTAMENTO");

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 16)); // NOI18N
        jLabel2.setText("Código:");

        campoNomeDep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeDepFocusLost(evt);
            }
        });
        campoNomeDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeDepActionPerformed(evt);
            }
        });
        campoNomeDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNomeDepKeyReleased(evt);
            }
        });

        campoCodDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodDepActionPerformed(evt);
            }
        });
        campoCodDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoCodDepKeyReleased(evt);
            }
        });

        btnSalvarDep.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        btnSalvarDep.setText("Salvar");
        btnSalvarDep.setEnabled(false);
        btnSalvarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDepActionPerformed(evt);
            }
        });

        btnCancelarDep.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        btnCancelarDep.setText("Cancelar");
        btnCancelarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDepartamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDepartamentos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodDep, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeDepActionPerformed

    private void btnCancelarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDepActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCancelarDepActionPerformed

    private void btnSalvarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDepActionPerformed
        // TODO add your handling code here:
     /*   String nome = campoNomeDep.getText();
        String codigo = campoCodDep.getText();
        
        Controller control = new Controller();
        control.addDepartments(codigo, nome);
*/
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUCadFunctionaries().setVisible(true);
            }
        });
        
        setVisible(false);
    }//GEN-LAST:event_btnSalvarDepActionPerformed

    private void campoNomeDepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeDepFocusLost
        // TODO add your handling code here:
        String nome = campoNomeDep.getText();
        
        
    }//GEN-LAST:event_campoNomeDepFocusLost

    private void campoNomeDepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeDepKeyReleased
        // TODO add your handling code here:
        if (campoNomeDep.getText().length()>0){
                btnSalvarDep.setEnabled(true);
                campoCodDepKeyReleased(evt);
            } else if (campoNomeDep.getText().length()<= 0) {
                btnSalvarDep.setEnabled(false);
            }
    }//GEN-LAST:event_campoNomeDepKeyReleased

    private void campoCodDepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodDepKeyReleased
        // TODO add your handling code here:
        if (campoCodDep.getText().length()>0){
                btnSalvarDep.setEnabled(true);
            } else if (campoCodDep.getText().length()<= 0) {
                btnSalvarDep.setEnabled(false);
        }
    }//GEN-LAST:event_campoCodDepKeyReleased

    private void campoCodDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadDepartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUCadDepartments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarDep;
    private javax.swing.JButton btnSalvarDep;
    private javax.swing.JTextField campoCodDep;
    private javax.swing.JTextField campoNomeDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDepartamentos;
    // End of variables declaration//GEN-END:variables
}
