/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.IU;

import java.util.logging.Level;
import java.util.logging.Logger;
import system_control.Controller;

/**
 *
 * @author gabri
 */

public class IURelatorioPesquisa extends javax.swing.JFrame {

    private Controller control = new Controller();

    /**
     * Creates new form IURelatorioPesquisa
     */
    public IURelatorioPesquisa() {
        initComponents();
        this.setTitle("Pesquisar relatórios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelRelatEscola = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campDeGastos = new javax.swing.JTextField();
        campDeSal = new javax.swing.JTextField();
        campAteGastos = new javax.swing.JTextField();
        campAteSal = new javax.swing.JTextField();
        labelCodInf = new javax.swing.JLabel();
        labelFuncNome = new javax.swing.JLabel();
        labelFuncCod = new javax.swing.JLabel();
        campNomeDep = new javax.swing.JTextField();
        campFunNome = new javax.swing.JTextField();
        campFunCod = new javax.swing.JTextField();
        btnMostrarRelatorio = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textRelatorios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelRelatEscola.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        labelRelatEscola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRelatEscola.setText("RELATÓRIOS DA ESCOLINHA ");
        labelRelatEscola.setToolTipText("");
        labelRelatEscola.setAutoscrolls(true);

        buttonGroup1.add(radio1);
        radio1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radio1.setText("Departamento em Faixa Específica de Gastos");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio2);
        radio2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radio2.setText("Funcionário em Faixa Específica de Salários");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio3);
        radio3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radio3.setText("Informações de um Departamento Específico");
        radio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio4);
        radio4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radio4.setText("Funcionários por Nome");
        radio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio5);
        radio5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        radio5.setText("Funcionário por Código");
        radio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel1.setText("De:");

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel2.setText("Até:");

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel3.setText("De:");

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel4.setText("Até:");

        campDeGastos.setEnabled(false);
        campDeGastos.setFocusCycleRoot(true);
        campDeGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                campDeGastosMouseReleased(evt);
            }
        });
        campDeGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campDeGastosActionPerformed(evt);
            }
        });
        campDeGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campDeGastosKeyReleased(evt);
            }
        });

        campDeSal.setEnabled(false);
        campDeSal.setFocusCycleRoot(true);
        campDeSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campDeSalActionPerformed(evt);
            }
        });
        campDeSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campDeSalKeyReleased(evt);
            }
        });

        campAteGastos.setEnabled(false);
        campAteGastos.setFocusCycleRoot(true);
        campAteGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campAteGastosKeyReleased(evt);
            }
        });

        campAteSal.setEnabled(false);
        campAteSal.setFocusCycleRoot(true);
        campAteSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campAteSalKeyReleased(evt);
            }
        });

        labelCodInf.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        labelCodInf.setText("Código:");

        labelFuncNome.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        labelFuncNome.setText("Nome:");

        labelFuncCod.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        labelFuncCod.setText("Código:");

        campNomeDep.setEnabled(false);
        campNomeDep.setFocusCycleRoot(true);
        campNomeDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campNomeDepKeyReleased(evt);
            }
        });

        campFunNome.setEnabled(false);
        campFunNome.setFocusCycleRoot(true);
        campFunNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campFunNomeKeyReleased(evt);
            }
        });

        campFunCod.setEnabled(false);
        campFunCod.setFocusCycleRoot(true);
        campFunCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campFunCodKeyReleased(evt);
            }
        });

        btnMostrarRelatorio.setText("Mostrar");
        btnMostrarRelatorio.setEnabled(false);
        btnMostrarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRelatorioActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        textRelatorios.setColumns(20);
        textRelatorios.setRows(5);
        jScrollPane1.setViewportView(textRelatorios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelRelatEscola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio3)
                            .addComponent(radio2)
                            .addComponent(radio4)
                            .addComponent(radio5)
                            .addComponent(radio1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFuncCod)
                                    .addComponent(labelFuncNome)
                                    .addComponent(labelCodInf))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campFunNome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campFunCod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campDeSal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campAteSal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campDeGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campAteGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnMostrarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRelatEscola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio1)
                    .addComponent(jLabel1)
                    .addComponent(campDeGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campAteGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio2)
                    .addComponent(jLabel3)
                    .addComponent(campDeSal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campAteSal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio3)
                    .addComponent(labelCodInf)
                    .addComponent(campNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio4)
                    .addComponent(labelFuncNome)
                    .addComponent(campFunNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio5)
                    .addComponent(labelFuncCod)
                    .addComponent(campFunCod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:

        if (radio1.isSelected()) {

            campDeGastos.setEnabled(radio1.isSelected());
            campAteGastos.setEnabled(radio1.isSelected());

            campFunCod.setEnabled(false);
            campFunNome.setEnabled(false);
            campAteSal.setEnabled(false);
            campDeSal.setEnabled(false);
            campNomeDep.setEnabled(false);

        }

    }//GEN-LAST:event_radio1ActionPerformed

    private void campDeSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campDeSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campDeSalActionPerformed

    private void radio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio5ActionPerformed
        // TODO add your handling code here:

        if (radio5.isSelected()) {
            campFunCod.setEnabled(radio5.isSelected());

            campDeGastos.setEnabled(false);
            campAteGastos.setEnabled(false);
            campFunNome.setEnabled(false);
            campAteSal.setEnabled(false);
            campDeSal.setEnabled(false);
            campNomeDep.setEnabled(false);

        }
    }//GEN-LAST:event_radio5ActionPerformed

    private void btnMostrarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRelatorioActionPerformed
        // TODO add your handling code here:
        if (radio1.isSelected()) {
            double de1 = Double.parseDouble(campDeGastos.getText());
            double ate1 = Double.parseDouble(campAteGastos.getText());
            try {
                textRelatorios.setText(control.showInfoDepartamentoFaixaEspecifica(de1, ate1));
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(IURelatorioPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (radio2.isSelected()) {
            double de1 = Double.parseDouble(campDeSal.getText());
            double ate1 = Double.parseDouble(campAteSal.getText());
            try {
                textRelatorios.setText(control.showFuncSalarioEspec(de1, ate1));
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(IURelatorioPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (radio3.isSelected()) {
            String code1 = (campNomeDep.getText());
            try {
                textRelatorios.setText(control.showInfoDepartamento(code1));
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(IURelatorioPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (radio4.isSelected()) {
            String nome2 = (campFunNome.getText());
            try {
                textRelatorios.setText(control.showFuncNome(nome2));
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(IURelatorioPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (radio5.isSelected()) {
            String code3 = (campFunCod.getText());
            try {
                textRelatorios.setText(control.showFuncCode(code3));
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(IURelatorioPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btnMostrarRelatorioActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        // TODO add your handling code here:

        if (radio2.isSelected()) {
            campAteSal.setEnabled(radio2.isSelected());
            campDeSal.setEnabled(radio2.isSelected());

            campFunCod.setEnabled(false);
            campDeGastos.setEnabled(false);
            campAteGastos.setEnabled(false);
            campFunNome.setEnabled(false);
            campNomeDep.setEnabled(false);

        }
    }//GEN-LAST:event_radio2ActionPerformed

    private void radio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio3ActionPerformed
        // TODO add your handling code here:
        if (radio3.isSelected()) {
            campNomeDep.setEnabled(radio3.isSelected());

            campAteSal.setEnabled(false);
            campDeSal.setEnabled(false);
            campFunCod.setEnabled(false);
            campDeGastos.setEnabled(false);
            campAteGastos.setEnabled(false);
            campFunNome.setEnabled(false);
        }

    }//GEN-LAST:event_radio3ActionPerformed

    private void radio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio4ActionPerformed
        // TODO add your handling code here:
        if (radio4.isSelected()) {
            campFunNome.setEnabled(radio4.isSelected());

            campNomeDep.setEnabled(false);
            campAteSal.setEnabled(false);
            campDeSal.setEnabled(false);
            campFunCod.setEnabled(false);
            campDeGastos.setEnabled(false);
            campAteGastos.setEnabled(false);

        }
    }//GEN-LAST:event_radio4ActionPerformed

    private void campDeGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campDeGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campDeGastosActionPerformed

    private void campDeGastosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campDeGastosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_campDeGastosMouseReleased

    private void campDeGastosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campDeGastosKeyReleased
        // TODO add your handling code here:
        if (campDeGastos.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
            campAteGastosKeyReleased(evt);
        } else if (campDeGastos.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }


    }//GEN-LAST:event_campDeGastosKeyReleased

    private void campAteGastosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campAteGastosKeyReleased
        // TODO add your handling code here:

        if (campAteGastos.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
        } else if (campAteGastos.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }
    }//GEN-LAST:event_campAteGastosKeyReleased

    private void campDeSalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campDeSalKeyReleased
        // TODO add your handling code here:
        if (campDeSal.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
            campAteSalKeyReleased(evt);
        } else if (campDeSal.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }
    }//GEN-LAST:event_campDeSalKeyReleased

    private void campAteSalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campAteSalKeyReleased
        // TODO add your handling code here:
        if (campAteSal.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
        } else if (campAteSal.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }
    }//GEN-LAST:event_campAteSalKeyReleased

    private void campNomeDepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campNomeDepKeyReleased
        // TODO add your handling code here:
        if (campNomeDep.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
        } else if (campNomeDep.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }
    }//GEN-LAST:event_campNomeDepKeyReleased

    private void campFunNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campFunNomeKeyReleased
        // TODO add your handling code here:
        if (campFunNome.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
        } else if (campFunNome.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }
    }//GEN-LAST:event_campFunNomeKeyReleased

    private void campFunCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campFunCodKeyReleased
        // TODO add your handling code here:
        if (campFunCod.getText().length() > 0) {
            btnMostrarRelatorio.setEnabled(true);
        } else if (campFunCod.getText().length() <= 0) {
            btnMostrarRelatorio.setEnabled(false);
        }
    }//GEN-LAST:event_campFunCodKeyReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        textRelatorios.setText("");

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IURelatorioPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IURelatorioPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IURelatorioPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IURelatorioPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IURelatorioPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrarRelatorio;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campAteGastos;
    private javax.swing.JTextField campAteSal;
    private javax.swing.JTextField campDeGastos;
    private javax.swing.JTextField campDeSal;
    private javax.swing.JTextField campFunCod;
    private javax.swing.JTextField campFunNome;
    private javax.swing.JTextField campNomeDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodInf;
    private javax.swing.JLabel labelFuncCod;
    private javax.swing.JLabel labelFuncNome;
    private javax.swing.JLabel labelRelatEscola;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JTextArea textRelatorios;
    // End of variables declaration//GEN-END:variables
}
